spring:
  application:
    name: notification-service
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:notificationdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # WebSocket Configuration
  websocket:
    endpoint: /ws
    application-destination-prefix: /app
    topic: /topic
    user-destination-prefix: /user

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.proxyapi: DEBUG

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
